---
title: "Data Acquisition For Reporting Analysis"
author: "Matthew Conger"
date: "3/11/2026"
format:
  html:
    code-fold: true
    toc: true
---

## Introduction

This data comes from two main sources. I used Yahoo Finance's API system to get historic data for all companies currently traded on the NASDAQ stock exchange. The other key element of this dataset is the dates that these companies filed their annual and quarterly reports, to get this I used the SEC EDGAR API system as well as a smaller API to convert ticker symbol (unique stock identifiers) into CIKs (a numeric unique identifier) so that I could request data from the SEC system.

I then combined and summarized these two sources into one large dataset which I will use to answer my question.

---

## Motivating Question

> **Do stock prices fully adjust on the day of an earnings announcement, or is there post-earnings drift?**

When companies announce their earnings, this has a direct effect on the stock price. For a long time it was accepted that this had an effect over the course of a few weeks after the report was published, this is what the post-earnings drift refers to. In more recent times due to the speed that the internet allows these reports to circulate, there are opinions that this adjustment is now absorbed into the stock price much more quickly (in this case synonymous with efficiently) some even believe that the price adjustment happens within the first day.

My aim is to compare the time of adjustment between pre 2010 markets and 2010-2025 markets to find if there is a statistically significant difference between the two.

---

## Data Sources

This project uses two primary data sources:

- **SEC EDGAR API** – used to obtain filing dates  
- **Yahoo Finance API** – used to obtain historical stock price data

Both data sources are widely used in financial research and are publicly accessible.

I also made sure to follow the guidelines given in the API documentation for each to make sure everything was as it should be. Also the fact that they have APIs in place is evidence that they want this data to be accessible.

### SEC EDGAR API

The U.S. Securities and Exchange Commission has an API available to access the data from their EDGAR system I used it to get:

- filing types (10-K, 10-Q, etc.)
- filing dates

[SEC EDGAR API Documentation](https://www.sec.gov/edgar/sec-api-documentation)

### Yahoo Finance

Yahoo Finance is where I got my historic data. It is a bit different since instead of using the normal requests package, Yahoo Finance has their own Python package to request data.

[yfinance GitHub Repository](https://github.com/ranaroussi/yfinance)

---

### Storing the data

For the historic stock market data, I saved each company's data as its own CSV where the name was ticker.csv so I could look through the directory and get any companies information.

For the filing dates, I saved the data in a JSON file with each company ticker as an object with two objects inside it with the two types of documents filed and a list of the dates those were filed.

---

### Combine the Datasets

To combine the data I loaded the JSON file with the filing dates then looped through each ticker, and for each one, I retrieved the associated csv file containing the data for that company. Then for each company I went through each filing date.

For each filing date I found 5 values:
-The percent change in stock price on that day
-The percent change in stock price on the next day
-The average percent change in stock price from 2 to 4 days after
-The average percent change in stock price from 5 to 10 days after
-The average percent change in stock price from 11 to 30 days after

Each one is a column along with the company ticker and the filing date.

---

## Overview of the Final Dataset

### Dataset Size

- **Rows:** `186,386`
- **Columns:** `7`

---

## Data Dictionary

Below is a simplified description of combined data.

| Feature | Description |
|-------|-------------|
| `ticker` | Stock ticker symbol |
| `filing_date` | Date the filing was submitted to the SEC |
| `close_pct_day0` | The percent change in stock price on the day of filing |
| `close_pct_day1` | The percent change in stock price on the day after filing |
| `mean_close_pct_days2_4` | The average percent change in stock price from 2 to 4 days after filing |
| `mean_close_pct_days5_10` | The average percent change in stock price from 5 to 10 days after filing |
| `mean_close_pct_days11_30` | The average percent change in stock price from 11 to 30 days after filing |



---

## Data Cleaning and Transformations

To make the data easy to use I did the following:

-convert the JSON files to CSVs 
-Made sure all dates were the same format
-Filtered filing types, only including quarterly and annual reports

---

## Data Quality Considerations

### Missing Data

- companies may have incomplete historical price data
- not all companies started at the same time so some have data going much farther back

### Coverage

The dataset only has companies who are traded on the NASDAQ, have historic data available, and file with the SEC.

---

## Reproducibility and Code

All code used to get the data is available here:

**[GitHub Repository – Project Code](https://github.com/Congerm/Data_Acquisition_Post-Earning_Drift)**

The repository includes:

- API data collection scripts
- cleaning and transformation steps
- dataset generation code

If you're interested in building similar datasets can use this code as a starting point.

---

## Further Resources

If you want to explore these data sources further, the following resources are helpful:

- [SEC EDGAR Company Filings](https://www.sec.gov/edgar/search/)
- [SEC API Documentation](https://www.sec.gov/edgar/sec-api-documentation)
- [yfinance Python Library](https://github.com/ranaroussi/yfinance)

These tools make it possible to build powerful financial datasets with relatively little infrastructure.

---

## Conclusion

This project shows how accessible data is and how we can aggregate many files to create a unique dataset and gain greater insight into new topics.